### YamlMime:TSType
name: OptionalConfig
uid: 'tp!OptionalConfig:interface'
package: tp!
fullName: OptionalConfig
summary: ''
remarks: ''
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: debug
    uid: 'tp!OptionalConfig#debug:member'
    package: tp!
    fullName: debug
    summary: ''
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'debug: boolean;'
      return:
        type: boolean
