### YamlMime:TSTypeAlias
name: APICONFIG
uid: 'bt!APICONFIG:type'
package: bt!
fullName: APICONFIG
summary: ''
remarks: ''
example: []
isPreview: false
isDeprecated: false
syntax: export type APICONFIG = z.infer<typeof configParser>;
