### YamlMime:TSTypeAlias
name: BaseConfig
uid: 'bt!BaseConfig:type'
package: bt!
fullName: BaseConfig
summary: ''
remarks: ''
example: []
isPreview: false
isDeprecated: false
syntax: export type BaseConfig = z.infer<typeof config>;
